#spring.application.name=back-end

spring.datasource.url=jdbc:postgresql://dpg-d6hd8mt6ubrc73bpllj0-a:5432/heltcheck
spring.datasource.username=heltcheck_user
spring.datasource.password=Ht6XqTBdHv0n6x4jeifipMpqwFhRUumA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect